### ISSUE TITLE
bug(airdrop): incorrect "unallocated amount" after admin withdraw

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/cw-nibiru#112] opened 2024-01-09 06:02 UTC
>  It’s working (i tested only for one user) but there’s a non critical bug:

> Once the funds of a campaign are withdrawn by the admin from the contract, the unallocated amount is not updated.
> You can successfully create a new reward to allocate to users, and these reward will be unable to be claimed by the user.

**Comment by k-yang** [comment] 2024-01-11 13:26
Some helpful context as the original author of the `airdrop` contract:

Leaving the contract in an invalid state after a withdraw was the original intended behavior, not a bug. 

"There is no check for if the total outstanding reward amount is greater than the amount of funds left in the contract. withdraw should only be called after the campaign ends because it could leave the contract in a state where it cannot fulfill a user's outstanding reward amount. Additional funds can be sent to the contract to reverse the withdrawal."

[Reference](https://github.com/NibiruChain/cw-nibiru/tree/179a302b990a3e605f5a54edde29bef7b3f4b753/contracts/airdrop)

In essence, `withdraw` was only meant to be called after a campaign has ended (e.g. 6 months post campaign launch), and users haven't come to claim their rewards yet. The campaign could then be abandoned and all the funds from the contract could be withdrawn. The leftover state in the campaign thus becomes useless.

An escape hatch to reverse the `withdraw` in case it was done erroneously is to just send back the funds that were withdrawn and the contract should work as intended again.

**Comment by matthiasmatt** [comment] 2024-02-26 10:39
Fixed in latest contract

**Closed by matthiasmatt** 2024-02-26 10:39 UTC
Labels: type: bug/fix
